In [1]:
# Numpy ===> 

# (1). same data type 
# (2). Memory consume less 
# (3). Computation Power 

In [2]:
import numpy as np 

In [3]:
a = [1,23,455,90]
type(a) 

list

In [4]:
b = np.array(a) 
b

array([  1,  23, 455,  90])

In [5]:
type(b) 

numpy.ndarray

# How to create a user defined array ? 

In [7]:
a = [] 
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter item:"))How can we check sha
    a.append(val) 
b = np.array(a) 
b

Enter size:3
Enter item:sam
Enter item:45
Enter item:raj


array(['sam', '45', 'raj'], dtype='<U3')

# How can we check shape and size of an array ? 

In [8]:
a = np.array([1,34,89,9900])

In [9]:
a

array([   1,   34,   89, 9900])

In [10]:
print("Total Shape = " , a.shape)
print("Total Elements = " , a.size)

Total Shape =  (4,)
Total Elements =  4


In [11]:
a = [[1,2,3] , [4,5,6] , [7,8,9]]
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# row_1 = [1,2,3]
# row_2 = [4,5,6]
# row_3 = [7,8,9]

# col_1 = [1,4,7]
# copl_2 = [2,5,8]
# col_3 = [3,6,9]

In [14]:
print("Total Shape = " , b.shape)
print("Total Elements = " , b.size)

Total Shape =  (3, 3)
Total Elements =  9


In [15]:
# iMAGES ===> pixels(0-255) ===> 0px black , 255 px white ==> Normalize(0-1)px 

# Intially weights ===> 0 , 1 


# optimization ===> 0,1 


# matrix ===> n(rows) , n(columns) 

# symmatric Matrix ===> n(rows) = n(columns) 

# Aymmatric Matrix ===> n(rows) !=n(columns) 

# [(1,1) , (2,2) , (3,3) , (4,4)......(n,n)]

# Prer-defined functions 

# (1). zeros() ===> It will create an array in which all the elements are 0 . 

In [16]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [17]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

# (2). ones() ===> It will create an array in which all the elments are 1 . 

In [18]:
a = np.ones(3)
a

array([1., 1., 1.])

In [23]:
a = np.ones((2 , 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
type(a) 

numpy.ndarray

In [27]:
a.shape

(2, 3)

In [28]:
a.size

6

# (3). eye() ====> In this function digonalpostional elements are 1 and rest all are zero . 

In [29]:
a = np.eye(4)    ####Symmatric Matrix 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
a = np.eye(3,4)  ####Asymmatric Matrix 
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])